### ISSUE TITLE
Kernel died in networkvisualization-tensorflow.ipynb

### ISSUE THREAD

**Issue by wendingp** [jingtinghuang/CS231n-Spring-2017#1]
Hi, do you know why Kernel died in networkvisualization-tensorflow.ipynb? How do you deal with the 3 squeezenetnet.ckpt.* files? See https://www.reddit.com/r/cs231n/comments/6fhz3z/assignment_3_squeezenet/

**Comment by w1ll1br0** [comment]
For the three files problem, I did exactly the same as the post from reddit. Rename the file and leave an additional copy(before renaminig) of the file. It worked pretty well for me. And since I'm not the one who said the kernel died in that post, I can't answer your question. I guessed they were talking about ipython kernel though.
